export const tabledata = [
  {
    id: 0,
    issuetype: 'Interactable Role',
    severity: 'Critical',
    component: 'ABC',
    selector: '.foo > #bar',
    url: 'https://www.zzzz.co.uk',
  },
  {
    id: 3,
    issuetype: 'Accessible Name',
    severity: 'Critical',
    component: 'AAA',
    selector: '.foo#bing > #bar',
    url: 'https://www.zzzz.co.uk',
  },
  {
    id: 2,
    issuetype: 'Interactable Role',
    severity: 'Minor',
    component: 'ABC',
    selector: '.some.class',
    url: 'https://www.aaa.co.uk',
  },
  {
    id: 16,
    issuetype: 'Keyboard Accessible',
    severity: 'Critical',
    component: 'ZZZ',
    selector: '#zooooom',
    url: 'https://www.zzzz.co.uk',
  },
  {
    id: 8,
    issuetype: 'Keyboard Accessiblee',
    severity: 'Minor',
    component: 'ABC',
    selector: '.vroooomo',
    url: 'https://www.fff.co.uk',
  },
  {
    id: 9,
    issuetype: 'Color Contrast',
    severity: 'Critical',
    component: 'ABC',
    selector: '#heythere',
    url: 'https://www.aaa.co.uk',
  },
  
];
